services:
  # Base de Datos
  db:
    image: mysql:8.0
    container_name: hiberus_db
    restart: always
    environment:
      MYSQL_DATABASE: hiberus_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  # PHP-FPM (Donde vive Symfony)
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: hiberus_php
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  # Servidor Web Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: hiberus_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
