nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        #allow_origin: ['http://localhost:5173']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        #'^/': null
        '^/api/':
            allow_origin: ['*'] # Para la prueba técnica, permitir todo es más rápido
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_headers: ['*']
            max_age: 3600

